[#8] Delete category created.
KarlReyes28/Expired pull request #28
Opened 2023-03-15 19:29 UTC by sandeepsingh8

2023-03-15 19:34 UTC, satgi requested changes
1. No issue is linked to this pull request, as a result, the issue will not be closed automatically once it's merged.
2. According to the [issue description](https://github.com/KarlReyes28/Expired/issues/8#issuecomment-1401004837), the following features are not implemented yet.

- [x] A category can only be deleted if no product is linked.
- [ ] A confirmation alert will show to ensure the user is sure of their action.

2023-03-17 21:42 UTC, donghua-shen commented on Expired/Views/CategoriesView.swift
> +//    @State private var category: String = ""
```suggestion

```

Delete unused variable

2023-03-17 21:50 UTC, donghua-shen commented on Expired/Views/CategoriesView.swift
> +    }
```suggestion

    private func deleteCategory(indexSet: IndexSet) {
        withAnimation {
            indexSet.map{productStore.categories[$0]}.forEach{ category in
                if category.products?.count ?? 0 > 0 {
                    showingNotDeleteAlert = true
                } else {
                   viewContext.delete(category)
                }
            }
            productStore.save(viewContext)
        }
    }

```

- space matters
- Avoid invoking `productStore.save` multiple times by moving it outside of the loop

2023-03-17 21:54 UTC, donghua-shen commented on Expired/Views/CategoriesView.swift
> +                Button("Ok", role: .cancel) {
```suggestion
                Button("OK", role: .cancel) {
```

- uppercase the "OK" text

2023-03-17 21:55 UTC, donghua-shen requested changes
Reviewed, thanks! 👍

2023-03-17 22:00 UTC, donghua-shen approved these changes

2023-03-17 22:00 UTC, merged