Expiring soon customize
KarlReyes28/Expired pull request #32
Opened 2023-03-25 17:08 UTC by KarlReyes28

closes #15 

-  Created expiring soon preference page.
- Reload notification once stepper has changed.

2023-03-25 20:12 UTC, donghua-shen commented
It appears that issue numbers are not included in the commit message, I'm afraid you'll have to reset your code locally and push force again.

2023-03-25 20:27 UTC, donghua-shen commented on Expired/Model/NotificationViewModel.swift
> +    @AppStorage("notifyExpirySoonDate") var days:Int = 2
- "notifyExpirySoonDate" can be renamed to "notifyExpiringSoonDays"
  - "ExpiringSoon" makes more sense than "ExpirySoon"
  - If it's "Date", it should be date type or something. As it is an Int, "Days" makes more sense
- "notifyExpirySoonDate" can be extracted as a constant value as it appears in multiple places
- `days:Int` -> `days: Int`, it looks better to add space between the variable name and data type
- Default value `2` can also be extracted as a constant as it appears in multiple places

2023-03-25 20:28 UTC, donghua-shen commented on Expired/Model/NotificationViewModel.swift
> +    }
```suggestion
```

Unused function, can be deleted

2023-03-25 20:29 UTC, donghua-shen commented on Expired/Model/NotificationViewModel.swift
>      // Schedule a notification of a given product and its notification category (expiring-soon | expired)
```suggestion

    // Schedule a notification of a given product and its notification category (expiring-soon | expired)
```

Add an empty line between functions

2023-03-25 20:34 UTC, donghua-shen commented on Expired/Model/NotificationViewModel.swift
> +                    notificationContent = "Expiring in \(numberString!) days"
```suggestion
                    notificationContent = "Expiring in \(numberString!) \(days > 1 ? "days" : "day")"
```

2023-03-25 20:36 UTC, donghua-shen commented on Expired/Model/ProductExtension.swift
>      var expiringSoonDate: Date? {
`dynamicDateExpiringSoon` can be combined with `expiringSoonDate`

2023-03-25 20:36 UTC, donghua-shen commented on Expired/Views/ExpiringSoonView.swift
> +    //    @State private var days  = 2
Unused code, can be deleted

2023-03-25 20:37 UTC, donghua-shen commented on Expired/Views/ExpiringSoonView.swift
> +    @AppStorage("notifyExpirySoonDate") private var days = 2
Please refer to https://github.com/KarlReyes28/Expired/pull/32/files#r1148428401

2023-03-25 20:38 UTC, donghua-shen commented on Expired/Views/ExpiringSoonView.swift
> +        VStack {
It can look better by adding padding to the content view.

2023-03-25 20:40 UTC, donghua-shen commented on Expired/Views/ExpiringSoonView.swift
> +                .font(.system(size:45, weight:.bold, design: .rounded))
```suggestion
                .font(.system(size: 45, weight: .bold, design: .rounded))
```

Apply consistent formatting: add space between `size:45` and `weight:.bold`

2023-03-25 20:41 UTC, donghua-shen commented on Expired/Views/ExpiringSoonView.swift
> +            Stepper("How many days would you like to be reminded of your product when it is going to be expired?", value: $days, in: 2...7)
I believe the days range that we discussed was 1...7, any updates on that?

2023-03-25 20:58 UTC, donghua-shen commented on Expired/Views/ExpiringSoonView.swift
> +                    UserDefaults.standard.set(days, forKey: "notifyExpirySoonDate" )
I believe `UserDefaults.standard.set(days, forKey: "notifyExpirySoonDate" )` is unnecessary as the `days` will be saved to User Defaults once the Stepper updated. That brings another two questions:

When should we update the notifications?
1. When pressing "Save": If a user didn't press "Save" after updating the Stepper, and went back to the previous screen to just closed the App, the App won't updates the notifications. That introduces inconsistent issue: say a user updates the `days` from 2 to 4 without pressing "Save", the notifications will still be 2 days before expiry date. We might have to introduce a local variable for the Stepper instead of binding the AppStorage variable directly to the Stepper, and only updates the AppStorage variable when a user press "Save", and updates notifications. _I suggestion this approach_.
2. When Stepper value updates: we need to add a watcher to updates notifications properly. This approach is more straight forward but introduces a potential issue. If a user updated the Stepper too fast, it will updates the notifications too frequently, which might cause data inconsistency issue of the notifications.

2023-03-25 21:01 UTC, donghua-shen commented on Expired/Views/ExpiringSoonView.swift
> +    }
```suggestion

    private var products: [Product] {        
        return productStore.unarchivedProducts
    }
```

Code formatting

2023-03-25 21:04 UTC, donghua-shen commented
Reviewed, thanks for the work 👍

2023-03-25 22:06 UTC, donghua-shen requested changes
Reviewed, thanks for the work 👍

2023-03-26 16:00 UTC, KarlReyes28 commented on Expired/Model/ProductExtension.swift
>      var expiringSoonDate: Date? {
so only one function to use for this?

2023-03-26 16:10 UTC, KarlReyes28 commented on Expired/Views/ExpiringSoonView.swift
> +            Stepper("How many days would you like to be reminded of your product when it is going to be expired?", value: $days, in: 2...7)
I forgot. Changing it to 1..7

2023-03-26 17:32 UTC, donghua-shen commented on Expired/Model/NotificationViewModel.swift
> +    @AppStorage("notifyExpirySoonDate") var days:Int = 2
Something like declaring global constant variables:
```
let APP_STORAGE_KEY_NOTIFY_EXPIRING_SOON_DAYS: String = "notifyExpiringSoonDays"
let DEFAULT_NOTIFY_EXPIRING_SOON_DAYS: Int = 2
```

Then use them somewhere else:
```
@AppStorage(APP_STORAGE_KEY_NOTIFY_EXPIRING_SOON_DAYS) var days: Int = DEFAULT_NOTIFY_EXPIRING_SOON_DAYS
```

Benefits:
- If we were to change the values, we only need to change the values of constant variables
- Avoid the potential spelling mistakes of hard coded String "notifyExpiringSoonDays" in multiple places

Sorry I don't quite understand "notifyExpirySoonDate and this?", can you elaborate on that?

2023-03-26 17:39 UTC, donghua-shen commented on Expired/Model/ProductExtension.swift
>      var expiringSoonDate: Date? {
Delete variable `dynamicDateExpiringSoon` and move its implementation into `expiringSoonDate`

```
    var expiringSoonDate: Date? {
        @AppStorage(APP_STORAGE_KEY_NOTIFY_EXPIRING_SOON_DAYS) var days: Int = DEFAULT_NOTIFY_EXPIRING_SOON_DAYS

        if let date = expiryDate {
            return Calendar.current.date(byAdding: .day, value: -days, to: date)
        }
        
        return nil
    }
```

BTW, in your current implementation of `expringSoonDate`, it should be `dynamicDateExpiringSoon ?? -2` instead of `dynamicDateExpiringSoon ?? 2`

2023-03-27 23:24 UTC, donghua-shen approved these changes

2023-03-27 23:26 UTC, merged